---

- name: create openssl rsa keys
  include_tasks: rsa.yml
  when: ssl_key_state == 'present'

- name: remove openssl rsa keys
  file:
    state: absent
    path: "{{ item }}"
  loop:
    - "{{ ssl_key_directory }}/{{ ssl_key_public_file }}"
    - "{{ ssl_key_directory }}/{{ ssl_key_private_file }}"
  when: ssl_key_state == 'absent'

- name: create hmac key
  include_tasks: hmac.yml
  when: hmac_key_state in [ 'present', 'regenerated' ]

- name: remove hmac key
  file:
    state: absent
    path: "{{ hmac_key_directory }}/{{ hmac_key_file }}"
  when: hmac_key_state == 'absent'
